spring:
  profiles:
    active: rest

  application:
    name: Heavy Metal Bake SaleL
  jackson:
    default-property-inclusion: non_null
sale:
  items:
    Brownie:
      name: Brownie
      code: B
      price: 65c
      amount: 48
    Muffin:
      name: Muffin
      code: M
      price: $1.00
      amount: 36
    Cake-Pop:
      name: Cake Pop
      code: C
      price: $1.35
      amount: 24
    Water:
      name: Water
      code: W
      price: $1.50
      amount: 30
logging:
  file:
    path: /logs/